### ISSUE TITLE
TravisCI isn't testing python3

### ISSUE THREAD

**Issue by perimosocordiae** [jsaponara/opentaxforms#7]
The TravisCI config still only lists Python 2.7, so it's not running the Python 3 test environment.

I'm not very familiar with tox and how it manages these things, so I'll leave the fix to someone else.

**Comment by jsaponara** [comment]
Fix will be in shortly, thanks CJ!

**Comment by jsaponara** [comment]
"Shortly" as in a year later!  Multiple python versions now tested in TravisCI as of 438b004.

**Comment by perimosocordiae** [comment]
I'll take it! :+1:
